### ISSUE TITLE
Error installing pyPDFeditor-GUI package due to PyQt5 and Qt installation issue.

### ISSUE THREAD

**Issue by aliafshany** [Augus1999/pyPDFeditor-GUI#3]
Hello there
i have an issue installing this app.

```
Processing /Users/f/Desktop/pyPDFeditor-GUI
  Preparing metadata (setup.py) ... done
Collecting PyMuPDF>=1.19.2 (from pyPDFeditor-GUI==2.2.5)
  Using cached PyMuPDF-1.22.3-cp311-cp311-macosx_11_0_arm64.whl (12.7 MB)
Collecting PyQt5>=5.15.4 (from pyPDFeditor-GUI==2.2.5)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w9/dly05fv51rj5_xn4bclzcd300000gn/T/pip-build-env-jc0an6qm/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/w9/dly05fv51rj5_xn4bclzcd300000gn/T/pip-build-env-jc0an6qm/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/w9/dly05fv51rj5_xn4bclzcd300000gn/T/pip-build-env-jc0an6qm/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 602, in setup
          self.update(tool)
        File "/private/var/folders/w9/dly05fv51rj5_xn4bclzcd300000gn/T/pip-install-7t3wb5p3/pyqt5_eb7abbbc9f514490a0b5f537b89e4ea7/project.py", line 165, in update
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Augus1999** [comment]
I'm sorry you encountered this problem.
It seems that Python 3.11 cannot build pyqt5 from source file. I recently have no MacOS machines, so the only suggestion I can give is to install the packages you want on Python 3.10 or 3.9.

**Comment by aliafshany** [comment]
@Augus1999 
thank you for replying.
