### ISSUE TITLE
Issue when trying to run program after successful install

### ISSUE THREAD

**Issue by c-alder** [Augus1999/pyPDFeditor-GUI#4]
The output from terminal:

PS C:\Users\----\Documents> pdfeditor
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pdfeditor.exe\__main__.py", line 4, in <module>
  File "c:\python37\lib\site-packages\pypdfeditor_core\__init__.py", line 12, in <module>
    from .application import reset, remove, Main, app_home
  File "c:\python37\lib\site-packages\pypdfeditor_core\application.py", line 17, in <module>
    from .windows import (
  File "c:\python37\lib\site-packages\pypdfeditor_core\windows.py", line 274, in <module>
    class MainR(QTabWidget):
  File "c:\python37\lib\site-packages\pypdfeditor_core\windows.py", line 515, in MainR
    def nativeEvent(self, event_type, message) -> tuple[bool, int]:
TypeError: 'type' object is not subscriptable

**Comment by Augus1999** [comment]
Thanks for your report. I have changed the type hint and hopefully that will solve this issue.

**Comment by c-alder** [comment]
Yep. Works great now, thank you!
